// https://en.wikipedia.org/wiki/Code_page_437

export interface Character {
  name: string,
  cp437: number,
  unicode: number
}

/**
 * Non-visible characters use [caret notation]{@link https://en.wikipedia.org/wiki/Caret_notation} to determine their display value.
 */
const Characters: { [key: string]: Character } = {
  Null:                                         { name: 'Null',                       cp437: 0x00, unicode: 0x0000 },
  StartOfHeading:                               { name: 'Start of Heading',           cp437: 0x01, unicode: 0x0001 },
  StartOfText:                                  { name: 'Start of Text',              cp437: 0x02, unicode: 0x0002 },
  EndOfText:                                    { name: 'End of Text',                cp437: 0x03, unicode: 0x0003 },
  EndOfTransmission:                            { name: 'End of Transmission',        cp437: 0x04, unicode: 0x0004 },
  Enquiry:                                      { name: 'Enquiry',                    cp437: 0x05, unicode: 0x0005 },
  Acknowledge:                                  { name: 'Acknowledgement',            cp437: 0x06, unicode: 0x0006 },
  Bell:                                         { name: 'Bell',                       cp437: 0x07, unicode: 0x0007 },
  Backspace:                                    { name: 'Backspace',                  cp437: 0x08, unicode: 0x0008 },
  HorizontalTabulation:                         { name: 'Horizontal Tab',             cp437: 0x09, unicode: 0x0009 },
  LineFeed:                                     { name: 'Line Feed',                  cp437: 0x0a, unicode: 0x000a },
  VerticalTabulation:                           { name: 'Vertical Tab',               cp437: 0x0b, unicode: 0x000b },
  FormFeed:                                     { name: 'Form Feed',                  cp437: 0x0c, unicode: 0x000c },
  CarriageReturn:                               { name: 'Carriage Return',            cp437: 0x0d, unicode: 0x000d },
  ShiftOut:                                     { name: 'Shift Out',                  cp437: 0x0e, unicode: 0x000e },
  ShiftIn:                                      { name: 'Shift In',                   cp437: 0x0f, unicode: 0x000f },
  DataLinkEscape:                               { name: 'Data Link Escape',           cp437: 0x10, unicode: 0x0010 },
  DeviceControlOne:                             { name: 'Device Control One',         cp437: 0x11, unicode: 0x0011 },
  DeviceControlTwo:                             { name: 'Device Control Two',         cp437: 0x12, unicode: 0x0012 },
  DeviceControlThree:                           { name: 'Device Control Three',       cp437: 0x13, unicode: 0x0013 },
  DeviceControlFour:                            { name: 'Device Control Four',        cp437: 0x14, unicode: 0x0014 },
  NegativeAcknowledge:                          { name: 'Negative Acknowledgement',   cp437: 0x15, unicode: 0x0015 },
  SynchronousIdle:                              { name: 'Synchronous Idle',           cp437: 0x16, unicode: 0x0016 },
  EndOfTransmissionBlock:                       { name: 'End of Transmission Block',  cp437: 0x17, unicode: 0x0017 },
  Cancel:                                       { name: 'Cancel',                     cp437: 0x18, unicode: 0x0018 },
  EndOfMedium:                                  { name: 'End Of Medium',              cp437: 0x19, unicode: 0x0019 },
  Substitute:                                   { name: 'Substitute',                 cp437: 0x1a, unicode: 0x001a },
  Escape:                                       { name: 'Escape',                     cp437: 0x1b, unicode: 0x001b },
  FileSeparator:                                { name: 'File Seperator',             cp437: 0x1c, unicode: 0x001c },
  GroupSeparator:                               { name: 'Group Seperator',            cp437: 0x1d, unicode: 0x001d },
  RecordSeparator:                              { name: 'Record Seperator',           cp437: 0x1e, unicode: 0x001e },
  UnitSeparator:                                { name: 'Unit Seperator',             cp437: 0x1f, unicode: 0x001f },
  Space:                                        { name: 'Space',                      cp437: 0x20, unicode: 0x0020 },
  ExclamationMark:                              { name: 'Exclamation Mark',           cp437: 0x21, unicode: 0x0021 },
  QuotationMark:                                { name: 'Quotes',                     cp437: 0x22, unicode: 0x0022 },
  NumberSign:                                   { name: 'Hash',                       cp437: 0x23, unicode: 0x0023 },
  DollarSign:                                   { name: 'Dollar',                     cp437: 0x24, unicode: 0x0024 },
  PercentSign:                                  { name: 'Percent',                    cp437: 0x25, unicode: 0x0025 },
  Ampersand:                                    { name: 'Ampersand',                  cp437: 0x26, unicode: 0x0026 },
  Apostrophe:                                   { name: 'Apostrophe',                 cp437: 0x27, unicode: 0x0027 },
  LeftParenthesis:                              { name: 'Left Parenthesis',           cp437: 0x28, unicode: 0x0028 },
  RightParenthesis:                             { name: 'Right Parenthesis',          cp437: 0x29, unicode: 0x0029 },
  Asterisk:                                     { name: 'Asterisk',                   cp437: 0x2a, unicode: 0x002a },
  PlusSign:                                     { name: 'Plus',                       cp437: 0x2b, unicode: 0x002b },
  Comma:                                        { name: 'Comma',                      cp437: 0x2c, unicode: 0x002c },
  HyphenMinus:                                  { name: 'Dash',                       cp437: 0x2d, unicode: 0x002d },
  FullStop:                                     { name: 'Period',                     cp437: 0x2e, unicode: 0x002e },
  Solidus:                                      { name: 'Slash',                      cp437: 0x2f, unicode: 0x002f },
  DigitZero:                                    { name: 'Zero',                       cp437: 0x30, unicode: 0x0030 },
  DigitOne:                                     { name: 'One',                        cp437: 0x31, unicode: 0x0031 },
  DigitTwo:                                     { name: 'Two',                        cp437: 0x32, unicode: 0x0032 },
  DigitThree:                                   { name: 'Three',                      cp437: 0x33, unicode: 0x0033 },
  DigitFour:                                    { name: 'Four',                       cp437: 0x34, unicode: 0x0034 },
  DigitFive:                                    { name: 'Five',                       cp437: 0x35, unicode: 0x0035 },
  DigitSix:                                     { name: 'Six',                        cp437: 0x36, unicode: 0x0036 },
  DigitSeven:                                   { name: 'Seven',                      cp437: 0x37, unicode: 0x0037 },
  DigitEight:                                   { name: 'Eight',                      cp437: 0x38, unicode: 0x0038 },
  DigitNine:                                    { name: 'Nine',                       cp437: 0x39, unicode: 0x0039 },
  Colon:                                        { name: 'Colon',                      cp437: 0x3a, unicode: 0x003a },
  Semicolon:                                    { name: 'Semicolon',                  cp437: 0x3b, unicode: 0x003b },
  LessThanSign:                                 { name: 'Less Than',                  cp437: 0x3c, unicode: 0x003c },
  EqualsSign:                                   { name: 'Equals',                     cp437: 0x3d, unicode: 0x003d },
  GreaterThanSign:                              { name: 'Greater Than',               cp437: 0x3e, unicode: 0x003e },
  QuestionMark:                                 { name: 'Question Mark',              cp437: 0x3f, unicode: 0x003f },
  CommercialAt:                                 { name: 'At',                         cp437: 0x40, unicode: 0x0040 },
  LatinCapitalLetterA:                          { name: 'A',                          cp437: 0x41, unicode: 0x0041 },
  LatinCapitalLetterB:                          { name: 'B',                          cp437: 0x42, unicode: 0x0042 },
  LatinCapitalLetterC:                          { name: 'C',                          cp437: 0x43, unicode: 0x0043 },
  LatinCapitalLetterD:                          { name: 'D',                          cp437: 0x44, unicode: 0x0044 },
  LatinCapitalLetterE:                          { name: 'E',                          cp437: 0x45, unicode: 0x0045 },
  LatinCapitalLetterF:                          { name: 'F',                          cp437: 0x46, unicode: 0x0046 },
  LatinCapitalLetterG:                          { name: 'G',                          cp437: 0x47, unicode: 0x0047 },
  LatinCapitalLetterH:                          { name: 'H',                          cp437: 0x48, unicode: 0x0048 },
  LatinCapitalLetterI:                          { name: 'I',                          cp437: 0x49, unicode: 0x0049 },
  LatinCapitalLetterJ:                          { name: 'J',                          cp437: 0x4a, unicode: 0x004a },
  LatinCapitalLetterK:                          { name: 'K',                          cp437: 0x4b, unicode: 0x004b },
  LatinCapitalLetterL:                          { name: 'L',                          cp437: 0x4c, unicode: 0x004c },
  LatinCapitalLetterM:                          { name: 'M',                          cp437: 0x4d, unicode: 0x004d },
  LatinCapitalLetterN:                          { name: 'N',                          cp437: 0x4e, unicode: 0x004e },
  LatinCapitalLetterO:                          { name: 'O',                          cp437: 0x4f, unicode: 0x004f },
  LatinCapitalLetterP:                          { name: 'P',                          cp437: 0x50, unicode: 0x0050 },
  LatinCapitalLetterQ:                          { name: 'Q',                          cp437: 0x51, unicode: 0x0051 },
  LatinCapitalLetterR:                          { name: 'R',                          cp437: 0x52, unicode: 0x0052 },
  LatinCapitalLetterS:                          { name: 'S',                          cp437: 0x53, unicode: 0x0053 },
  LatinCapitalLetterT:                          { name: 'T',                          cp437: 0x54, unicode: 0x0054 },
  LatinCapitalLetterU:                          { name: 'U',                          cp437: 0x55, unicode: 0x0055 },
  LatinCapitalLetterV:                          { name: 'V',                          cp437: 0x56, unicode: 0x0056 },
  LatinCapitalLetterW:                          { name: 'W',                          cp437: 0x57, unicode: 0x0057 },
  LatinCapitalLetterX:                          { name: 'X',                          cp437: 0x58, unicode: 0x0058 },
  LatinCapitalLetterY:                          { name: 'Y',                          cp437: 0x59, unicode: 0x0059 },
  LatinCapitalLetterZ:                          { name: 'Z',                          cp437: 0x5a, unicode: 0x005a },
  LeftSquareBracket:                            { name: 'Left Square Bracket',        cp437: 0x5b, unicode: 0x005b },
  ReverseSolidus:                               { name: 'Backslash',                  cp437: 0x5c, unicode: 0x005c },
  RightSquareBracket:                           { name: 'Right Square Bracket',       cp437: 0x5d, unicode: 0x005d },
  CircumflexAccent:                             { name: 'Caret',                      cp437: 0x5e, unicode: 0x005e },
  LowLine:                                      { name: 'Underscore',                 cp437: 0x5f, unicode: 0x005f },
  GraveAccent:                                  { name: 'Accent Grave',               cp437: 0x60, unicode: 0x0060 },
  LatinSmallLetterA:                            { name: 'a',                          cp437: 0x61, unicode: 0x0061 },
  LatinSmallLetterB:                            { name: 'b',                          cp437: 0x62, unicode: 0x0062 },
  LatinSmallLetterC:                            { name: 'c',                          cp437: 0x63, unicode: 0x0063 },
  LatinSmallLetterD:                            { name: 'd',                          cp437: 0x64, unicode: 0x0064 },
  LatinSmallLetterE:                            { name: 'e',                          cp437: 0x65, unicode: 0x0065 },
  LatinSmallLetterF:                            { name: 'f',                          cp437: 0x66, unicode: 0x0066 },
  LatinSmallLetterG:                            { name: 'g',                          cp437: 0x67, unicode: 0x0067 },
  LatinSmallLetterH:                            { name: 'h',                          cp437: 0x68, unicode: 0x0068 },
  LatinSmallLetterI:                            { name: 'i',                          cp437: 0x69, unicode: 0x0069 },
  LatinSmallLetterJ:                            { name: 'j',                          cp437: 0x6a, unicode: 0x006a },
  LatinSmallLetterK:                            { name: 'k',                          cp437: 0x6b, unicode: 0x006b },
  LatinSmallLetterL:                            { name: 'l',                          cp437: 0x6c, unicode: 0x006c },
  LatinSmallLetterM:                            { name: 'm',                          cp437: 0x6d, unicode: 0x006d },
  LatinSmallLetterN:                            { name: 'n',                          cp437: 0x6e, unicode: 0x006e },
  LatinSmallLetterO:                            { name: 'o',                          cp437: 0x6f, unicode: 0x006f },
  LatinSmallLetterP:                            { name: 'p',                          cp437: 0x70, unicode: 0x0070 },
  LatinSmallLetterQ:                            { name: 'q',                          cp437: 0x71, unicode: 0x0071 },
  LatinSmallLetterR:                            { name: 'r',                          cp437: 0x72, unicode: 0x0072 },
  LatinSmallLetterS:                            { name: 's',                          cp437: 0x73, unicode: 0x0073 },
  LatinSmallLetterT:                            { name: 't',                          cp437: 0x74, unicode: 0x0074 },
  LatinSmallLetterU:                            { name: 'u',                          cp437: 0x75, unicode: 0x0075 },
  LatinSmallLetterV:                            { name: 'v',                          cp437: 0x76, unicode: 0x0076 },
  LatinSmallLetterW:                            { name: 'w',                          cp437: 0x77, unicode: 0x0077 },
  LatinSmallLetterX:                            { name: 'x',                          cp437: 0x78, unicode: 0x0078 },
  LatinSmallLetterY:                            { name: 'y',                          cp437: 0x79, unicode: 0x0079 },
  LatinSmallLetterZ:                            { name: 'z',                          cp437: 0x7a, unicode: 0x007a },
  LeftCurlyBracket:                             { name: 'Left Curly Brace',           cp437: 0x7b, unicode: 0x007b },
  VerticalLine:                                 { name: 'Pipe',                       cp437: 0x7c, unicode: 0x007c },
  RightCurlyBracket:                            { name: 'Right Curly Brace',          cp437: 0x7d, unicode: 0x007d },
  Tilde:                                        { name: 'Tilde',                      cp437: 0x7e, unicode: 0x007e },
  Delete:                                       { name: 'Delete',                     cp437: 0x7f, unicode: 0x007f },
  LatinCapitalLetterCWithCedilla:               { name: 'LATIN CAPITAL LETTER C WITH CEDILLA', cp437: 0x80, unicode: 0x00c7 },
  LatinSmallLetterUWithDiaeresis:               { name: 'LATIN SMALL LETTER U WITH DIAERESIS', cp437: 0x81, unicode: 0x00fc },
  LatinSmallLetterEWithAcute:                   { name: 'LATIN SMALL LETTER E WITH ACUTE', cp437: 0x82, unicode: 0x00e9 },
  LatinSmallLetterAWithCircumflex:              { name: 'LATIN SMALL LETTER A WITH CIRCUMFLEX', cp437: 0x83, unicode: 0x00e2 },
  LatinSmallLetterAWithDiaeresis:               { name: 'LATIN SMALL LETTER A WITH DIAERESIS', cp437: 0x84, unicode: 0x00e4 },
  LatinSmallLetterAWithGrave:                   { name: 'LATIN SMALL LETTER A WITH GRAVE', cp437: 0x85, unicode: 0x00e0 },
  LatinSmallLetterAWithRingAbove:               { name: 'LATIN SMALL LETTER A WITH RING ABOVE', cp437: 0x86, unicode: 0x00e5 },
  LatinSmallLetterCWithCedilla:                 { name: 'LATIN SMALL LETTER C WITH CEDILLA', cp437: 0x87, unicode: 0x00e7 },
  LatinSmallLetterEWithCircumflex:              { name: 'LATIN SMALL LETTER E WITH CIRCUMFLEX', cp437: 0x88, unicode: 0x00ea },
  LatinSmallLetterEWithDiaeresis:               { name: 'LATIN SMALL LETTER E WITH DIAERESIS', cp437: 0x89, unicode: 0x00eb },
  LatinSmallLetterEWithGrave:                   { name: 'LATIN SMALL LETTER E WITH GRAVE', cp437: 0x8a, unicode: 0x00e8 },
  LatinSmallLetterIWithDiaeresis:               { name: 'LATIN SMALL LETTER I WITH DIAERESIS', cp437: 0x8b, unicode: 0x00ef },
  LatinSmallLetterIWithCircumflex:              { name: 'LATIN SMALL LETTER I WITH CIRCUMFLEX', cp437: 0x8c, unicode: 0x00ee },
  LatinSmallLetterIWithGrave:                   { name: 'LATIN SMALL LETTER I WITH GRAVE', cp437: 0x8d, unicode: 0x00ec },
  LatinCapitalLetterAWithDiaeresis:             { name: 'LATIN CAPITAL LETTER A WITH DIAERESIS', cp437: 0x8e, unicode: 0x00c4 },
  LatinCapitalLetterAWithRingAbove:             { name: 'LATIN CAPITAL LETTER A WITH RING ABOVE', cp437: 0x8f, unicode: 0x00c5 },
  LatinCapitalLetterEWithAcute:                 { name: 'LATIN CAPITAL LETTER E WITH ACUTE', cp437: 0x90, unicode: 0x00c9 },
  LatinSmallLigatureAe:                         { name: 'LATIN SMALL LIGATURE AE', cp437: 0x91, unicode: 0x00e6 },
  LatinCapitalLigatureAe:                       { name: 'LATIN CAPITAL LIGATURE AE', cp437: 0x92, unicode: 0x00c6 },
  LatinSmallLetterOWithCircumflex:              { name: 'LATIN SMALL LETTER O WITH CIRCUMFLEX', cp437: 0x93, unicode: 0x00f4 },
  LatinSmallLetterOWithDiaeresis:               { name: 'LATIN SMALL LETTER O WITH DIAERESIS', cp437: 0x94, unicode: 0x00f6 },
  LatinSmallLetterOWithGrave:                   { name: 'LATIN SMALL LETTER O WITH GRAVE', cp437: 0x95, unicode: 0x00f2 },
  LatinSmallLetterUWithCircumflex:              { name: 'LATIN SMALL LETTER U WITH CIRCUMFLEX', cp437: 0x96, unicode: 0x00fb },
  LatinSmallLetterUWithGrave:                   { name: 'LATIN SMALL LETTER U WITH GRAVE', cp437: 0x97, unicode: 0x00f9 },
  LatinSmallLetterYWithDiaeresis:               { name: 'LATIN SMALL LETTER Y WITH DIAERESIS', cp437: 0x98, unicode: 0x00ff },
  LatinCapitalLetterOWithDiaeresis:             { name: 'LATIN CAPITAL LETTER O WITH DIAERESIS', cp437: 0x99, unicode: 0x00d6 },
  LatinCapitalLetterUWithDiaeresis:             { name: 'LATIN CAPITAL LETTER U WITH DIAERESIS', cp437: 0x9a, unicode: 0x00dc },
  CentSign:                                     { name: 'CENT SIGN', cp437: 0x9b, unicode: 0x00a2 },
  PoundSign:                                    { name: 'POUND SIGN', cp437: 0x9c, unicode: 0x00a3 },
  YenSign:                                      { name: 'YEN SIGN', cp437: 0x9d, unicode: 0x00a5 },
  PesetaSign:                                   { name: 'PESETA SIGN', cp437: 0x9e, unicode: 0x20a7 },
  LatinSmallLetterFWithHook:                    { name: 'LATIN SMALL LETTER F WITH HOOK', cp437: 0x9f, unicode: 0x0192 },
  LatinSmallLetterAWithAcute:                   { name: 'LATIN SMALL LETTER A WITH ACUTE', cp437: 0xa0, unicode: 0x00e1 },
  LatinSmallLetterIWithAcute:                   { name: 'LATIN SMALL LETTER I WITH ACUTE', cp437: 0xa1, unicode: 0x00ed },
  LatinSmallLetterOWithAcute:                   { name: 'LATIN SMALL LETTER O WITH ACUTE', cp437: 0xa2, unicode: 0x00f3 },
  LatinSmallLetterUWithAcute:                   { name: 'LATIN SMALL LETTER U WITH ACUTE', cp437: 0xa3, unicode: 0x00fa },
  LatinSmallLetterNWithTilde:                   { name: 'LATIN SMALL LETTER N WITH TILDE', cp437: 0xa4, unicode: 0x00f1 },
  LatinCapitalLetterNWithTilde:                 { name: 'LATIN CAPITAL LETTER N WITH TILDE', cp437: 0xa5, unicode: 0x00d1 },
  FeminineOrdinalIndicator:                     { name: 'FEMININE ORDINAL INDICATOR', cp437: 0xa6, unicode: 0x00aa },
  MasculineOrdinalIndicator:                    { name: 'MASCULINE ORDINAL INDICATOR', cp437: 0xa7, unicode: 0x00ba },
  InvertedQuestionMark:                         { name: 'INVERTED QUESTION MARK', cp437: 0xa8, unicode: 0x00bf },
  ReversedNotSign:                              { name: 'REVERSED NOT SIGN', cp437: 0xa9, unicode: 0x2310 },
  NotSign:                                      { name: 'NOT SIGN', cp437: 0xaa, unicode: 0x00ac },
  VulgarFractionOneHalf:                        { name: 'VULGAR FRACTION ONE HALF', cp437: 0xab, unicode: 0x00bd },
  VulgarFractionOneQuarter:                     { name: 'VULGAR FRACTION ONE QUARTER', cp437: 0xac, unicode: 0x00bc },
  InvertedExclamationMark:                      { name: 'INVERTED EXCLAMATION MARK', cp437: 0xad, unicode: 0x00a1 },
  LeftPointingDoubleAngleQuotationMark:         { name: 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK', cp437: 0xae, unicode: 0x00ab },
  RightPointingDoubleAngleQuotationMark:        { name: 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK', cp437: 0xaf, unicode: 0x00bb },
  LightShade:                                   { name: 'LIGHT SHADE', cp437: 0xb0, unicode: 0x2591 },
  MediumShade:                                  { name: 'MEDIUM SHADE', cp437: 0xb1, unicode: 0x2592 },
  DarkShade:                                    { name: 'DARK SHADE', cp437: 0xb2, unicode: 0x2593 },
  BoxDrawingsLightVertical:                     { name: 'BOX DRAWINGS LIGHT VERTICAL', cp437: 0xb3, unicode: 0x2502 },
  BoxDrawingsLightVerticalAndLeft:              { name: 'BOX DRAWINGS LIGHT VERTICAL AND LEFT', cp437: 0xb4, unicode: 0x2524 },
  BoxDrawingsVerticalSingleAndLeftDouble:       { name: 'BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE', cp437: 0xb5, unicode: 0x2561 },
  BoxDrawingsVerticalDoubleAndLeftSingle:       { name: 'BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE', cp437: 0xb6, unicode: 0x2562 },
  BoxDrawingsDownDoubleAndLeftSingle:           { name: 'BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE', cp437: 0xb7, unicode: 0x2556 },
  BoxDrawingsDownSingleAndLeftDouble:           { name: 'BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE', cp437: 0xb8, unicode: 0x2555 },
  BoxDrawingsDoubleVerticalAndLeft:             { name: 'BOX DRAWINGS DOUBLE VERTICAL AND LEFT', cp437: 0xb9, unicode: 0x2563 },
  BoxDrawingsDoubleVertical:                    { name: 'BOX DRAWINGS DOUBLE VERTICAL', cp437: 0xba, unicode: 0x2551 },
  BoxDrawingsDoubleDownAndLeft:                 { name: 'BOX DRAWINGS DOUBLE DOWN AND LEFT', cp437: 0xbb, unicode: 0x2557 },
  BoxDrawingsDoubleUpAndLeft:                   { name: 'BOX DRAWINGS DOUBLE UP AND LEFT', cp437: 0xbc, unicode: 0x255d },
  BoxDrawingsUpDoubleAndLeftSingle:             { name: 'BOX DRAWINGS UP DOUBLE AND LEFT SINGLE', cp437: 0xbd, unicode: 0x255c },
  BoxDrawingsUpSingleAndLeftDouble:             { name: 'BOX DRAWINGS UP SINGLE AND LEFT DOUBLE', cp437: 0xbe, unicode: 0x255b },
  BoxDrawingsLightDownAndLeft:                  { name: 'BOX DRAWINGS LIGHT DOWN AND LEFT', cp437: 0xbf, unicode: 0x2510 },
  BoxDrawingsLightUpAndRight:                   { name: 'BOX DRAWINGS LIGHT UP AND RIGHT', cp437: 0xc0, unicode: 0x2514 },
  BoxDrawingsLightUpAndHorizontal:              { name: 'BOX DRAWINGS LIGHT UP AND HORIZONTAL', cp437: 0xc1, unicode: 0x2534 },
  BoxDrawingsLightDownAndHorizontal:            { name: 'BOX DRAWINGS LIGHT DOWN AND HORIZONTAL', cp437: 0xc2, unicode: 0x252c },
  BoxDrawingsLightVerticalAndRight:             { name: 'BOX DRAWINGS LIGHT VERTICAL AND RIGHT', cp437: 0xc3, unicode: 0x251c },
  BoxDrawingsLightHorizontal:                   { name: 'BOX DRAWINGS LIGHT HORIZONTAL', cp437: 0xc4, unicode: 0x2500 },
  BoxDrawingsLightVerticalAndHorizontal:        { name: 'BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL', cp437: 0xc5, unicode: 0x253c },
  BoxDrawingsVerticalSingleAndRightDouble:      { name: 'BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE', cp437: 0xc6, unicode: 0x255e },
  BoxDrawingsVerticalDoubleAndRightSingle:      { name: 'BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE', cp437: 0xc7, unicode: 0x255f },
  BoxDrawingsDoubleUpAndRight:                  { name: 'BOX DRAWINGS DOUBLE UP AND RIGHT', cp437: 0xc8, unicode: 0x255a },
  BoxDrawingsDoubleDownAndRight:                { name: 'BOX DRAWINGS DOUBLE DOWN AND RIGHT', cp437: 0xc9, unicode: 0x2554 },
  BoxDrawingsDoubleUpAndHorizontal:             { name: 'BOX DRAWINGS DOUBLE UP AND HORIZONTAL', cp437: 0xca, unicode: 0x2569 },
  BoxDrawingsDoubleDownAndHorizontal:           { name: 'BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL', cp437: 0xcb, unicode: 0x2566 },
  BoxDrawingsDoubleVerticalAndRight:            { name: 'BOX DRAWINGS DOUBLE VERTICAL AND RIGHT', cp437: 0xcc, unicode: 0x2560 },
  BoxDrawingsDoubleHorizontal:                  { name: 'BOX DRAWINGS DOUBLE HORIZONTAL', cp437: 0xcd, unicode: 0x2550 },
  BoxDrawingsDoubleVerticalAndHorizontal:       { name: 'BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL', cp437: 0xce, unicode: 0x256c },
  BoxDrawingsUpSingleAndHorizontalDouble:       { name: 'BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE', cp437: 0xcf, unicode: 0x2567 },
  BoxDrawingsUpDoubleAndHorizontalSingle:       { name: 'BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE', cp437: 0xd0, unicode: 0x2568 },
  BoxDrawingsDownSingleAndHorizontalDouble:     { name: 'BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE', cp437: 0xd1, unicode: 0x2564 },
  BoxDrawingsDownDoubleAndHorizontalSingle:     { name: 'BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE', cp437: 0xd2, unicode: 0x2565 },
  BoxDrawingsUpDoubleAndRightSingle:            { name: 'BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE', cp437: 0xd3, unicode: 0x2559 },
  BoxDrawingsUpSingleAndRightDouble:            { name: 'BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE', cp437: 0xd4, unicode: 0x2558 },
  BoxDrawingsDownSingleAndRightDouble:          { name: 'BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE', cp437: 0xd5, unicode: 0x2552 },
  BoxDrawingsDownDoubleAndRightSingle:          { name: 'BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE', cp437: 0xd6, unicode: 0x2553 },
  BoxDrawingsVerticalDoubleAndHorizontalSingle: { name: 'BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE', cp437: 0xd7, unicode: 0x256b },
  BoxDrawingsVerticalSingleAndHorizontalDouble: { name: 'BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE', cp437: 0xd8, unicode: 0x256a },
  BoxDrawingsLightUpAndLeft:                    { name: 'BOX DRAWINGS LIGHT UP AND LEFT', cp437: 0xd9, unicode: 0x2518 },
  BoxDrawingsLightDownAndRight:                 { name: 'BOX DRAWINGS LIGHT DOWN AND RIGHT', cp437: 0xda, unicode: 0x250c },
  FullBlock:                                    { name: 'FULL BLOCK', cp437: 0xdb, unicode: 0x2588 },
  LowerHalfBlock:                               { name: 'LOWER HALF BLOCK', cp437: 0xdc, unicode: 0x2584 },
  LeftHalfBlock:                                { name: 'LEFT HALF BLOCK', cp437: 0xdd, unicode: 0x258c },
  RightHalfBlock:                               { name: 'RIGHT HALF BLOCK', cp437: 0xde, unicode: 0x2590 },
  UpperHalfBlock:                               { name: 'UPPER HALF BLOCK', cp437: 0xdf, unicode: 0x2580 },
  GreekSmallLetterAlpha:                        { name: 'GREEK SMALL LETTER ALPHA', cp437: 0xe0, unicode: 0x03b1 },
  LatinSmallLetterSharpS:                       { name: 'LATIN SMALL LETTER SHARP S', cp437: 0xe1, unicode: 0x00df },
  GreekCapitalLetterGamma:                      { name: 'GREEK CAPITAL LETTER GAMMA', cp437: 0xe2, unicode: 0x0393 },
  GreekSmallLetterPi:                           { name: 'GREEK SMALL LETTER PI', cp437: 0xe3, unicode: 0x03c0 },
  GreekCapitalLetterSigma:                      { name: 'GREEK CAPITAL LETTER SIGMA', cp437: 0xe4, unicode: 0x03a3 },
  GreekSmallLetterSigma:                        { name: 'GREEK SMALL LETTER SIGMA', cp437: 0xe5, unicode: 0x03c3 },
  MicroSign:                                    { name: 'MICRO SIGN', cp437: 0xe6, unicode: 0x00b5 },
  GreekSmallLetterTau:                          { name: 'GREEK SMALL LETTER TAU', cp437: 0xe7, unicode: 0x03c4 },
  GreekCapitalLetterPhi:                        { name: 'GREEK CAPITAL LETTER PHI', cp437: 0xe8, unicode: 0x03a6 },
  GreekCapitalLetterTheta:                      { name: 'GREEK CAPITAL LETTER THETA', cp437: 0xe9, unicode: 0x0398 },
  GreekCapitalLetterOmega:                      { name: 'GREEK CAPITAL LETTER OMEGA', cp437: 0xea, unicode: 0x03a9 },
  GreekSmallLetterDelta:                        { name: 'GREEK SMALL LETTER DELTA', cp437: 0xeb, unicode: 0x03b4 },
  Infinity:                                     { name: 'INFINITY', cp437: 0xec, unicode: 0x221e },
  GreekSmallLetterPhi:                          { name: 'GREEK SMALL LETTER PHI', cp437: 0xed, unicode: 0x03c6 },
  GreekSmallLetterEpsilon:                      { name: 'GREEK SMALL LETTER EPSILON', cp437: 0xee, unicode: 0x03b5 },
  Intersection:                                 { name: 'INTERSECTION', cp437: 0xef, unicode: 0x2229 },
  IdenticalTo:                                  { name: 'IDENTICAL TO', cp437: 0xf0, unicode: 0x2261 },
  PlusMinusSign:                                { name: 'PLUS-MINUS SIGN', cp437: 0xf1, unicode: 0x00b1 },
  GreaterThanOrEqualTo:                         { name: 'GREATER-THAN OR EQUAL TO', cp437: 0xf2, unicode: 0x2265 },
  LessThanOrEqualTo:                            { name: 'LESS-THAN OR EQUAL TO', cp437: 0xf3, unicode: 0x2264 },
  TopHalfIntegral:                              { name: 'TOP HALF INTEGRAL', cp437: 0xf4, unicode: 0x2320 },
  BottomHalfIntegral:                           { name: 'BOTTOM HALF INTEGRAL', cp437: 0xf5, unicode: 0x2321 },
  DivisionSign:                                 { name: 'DIVISION SIGN', cp437: 0xf6, unicode: 0x00f7 },
  AlmostEqualTo:                                { name: 'ALMOST EQUAL TO', cp437: 0xf7, unicode: 0x2248 },
  DegreeSign:                                   { name: 'DEGREE SIGN', cp437: 0xf8, unicode: 0x00b0 },
  BulletOperator:                               { name: 'BULLET OPERATOR', cp437: 0xf9, unicode: 0x2219 },
  MiddleDot:                                    { name: 'MIDDLE DOT', cp437: 0xfa, unicode: 0x00b7 },
  SquareRoot:                                   { name: 'SQUARE ROOT', cp437: 0xfb, unicode: 0x221a },
  SuperscriptLatinSmallLetterN:                 { name: 'SUPERSCRIPT LATIN SMALL LETTER N', cp437: 0xfc, unicode: 0x207f },
  SuperscriptTwo:                               { name: 'SUPERSCRIPT TWO', cp437: 0xfd, unicode: 0x00b2 },
  BlackSquare:                                  { name: 'BLACK SQUARE', cp437: 0xfe, unicode: 0x25a0 },
  NoBreakSpace:                                 { name: 'NO-BREAK SPACE', cp437: 0xff, unicode: 0x00a0 }
};

export default Characters;

export function convertCP437toUTF8(byte) {
  const character = Object.values(Characters).find(c => c.cp437 === byte);
  if (!character) throw new Error(`unknown CP437 key code: ${byte}`);
  return character.unicode;
}
