// https://en.wikipedia.org/wiki/ASCII#ASCII_control_code_chart

export interface Character {
  name: string,
  abbreviation: string,
  display: string,
  byte: number
}

/**
 * Non-visible characters use [caret notation]{@link https://en.wikipedia.org/wiki/Caret_notation} to determine their display value.
 */
const Characters: { [key: string]: Character } = {
  Null:                     { name: 'Null',                       abbreviation: 'NUL', display: '^@', byte: 0 },
  StartOfHeading:           { name: 'Start of Heading',           abbreviation: 'SOH', display: '^A', byte: 1 },
  StartOfText:              { name: 'Start of Text',              abbreviation: 'STX', display: '^B', byte: 2 },
  EndOfText:                { name: 'End of Text',                abbreviation: 'ETX', display: '^C', byte: 3 },
  EndOfTransmission:        { name: 'End of Transmission',        abbreviation: 'EOT', display: '^D', byte: 4 },
  Enquiry:                  { name: 'Enquiry',                    abbreviation: 'ENQ', display: '^E', byte: 5 },
  Acknowledgement:          { name: 'Acknowledgement',            abbreviation: 'ACK', display: '^F', byte: 6 },
  Bell:                     { name: 'Bell',                       abbreviation: 'BEL', display: '^G', byte: 7 },
  Backspace:                { name: 'Backspace',                  abbreviation: '', display: '^H', byte: 8 },
  HorizontalTab:            { name: 'Horizontal Tab',             abbreviation: '', display: '^I', byte: 9 },
  LineFeed:                 { name: 'Line Feed',                  abbreviation: '', display: '^J', byte: 10 },
  VerticalTab:              { name: 'Vertical Tab',               abbreviation: '', display: '^K', byte: 11 },
  FormFeed:                 { name: 'Form Feed',                  abbreviation: '', display: '^L', byte: 12 },
  CarriageReturn:           { name: 'Carriage Return',            abbreviation: '', display: '^M', byte: 13 },
  ShiftOut:                 { name: 'Shift Out',                  abbreviation: '', display: '^N', byte: 14 },
  ShiftIn:                  { name: 'Shift In',                   abbreviation: '', display: '^O', byte: 15 },
  DataLinkEscape:           { name: 'Data Link Escape',           abbreviation: '', display: '^P', byte: 16 },
  DeviceControlOne:         { name: 'Device Control One',         abbreviation: '', display: '^Q', byte: 17 },
  DeviceControlTwo:         { name: 'Device Control Two',         abbreviation: '', display: '^R', byte: 18 },
  DeviceControlThree:       { name: 'Device Control Three',       abbreviation: '', display: '^S', byte: 19 },
  DeviceControlFour:        { name: 'Device Control Four',        abbreviation: '', display: '^T', byte: 20 },
  NegativeAcknowledgement:  { name: 'Negative Acknowledgement',   abbreviation: '', display: '^U', byte: 21 },
  SynchronousIdle:          { name: 'Synchronous Idle',           abbreviation: '', display: '^V', byte: 22 },
  EndOfTransmissionBlock:   { name: 'End of Transmission Block',  abbreviation: '', display: '^W', byte: 23 },
  Cancel:                   { name: 'Cancel',                     abbreviation: '', display: '^X', byte: 24 },
  EndOfMedium:              { name: 'End Of Medium',              abbreviation: '', display: '^Y', byte: 25 },
  Substitute:               { name: 'Substitute',                 abbreviation: '', display: '^Z', byte: 26 },
  Escape:                   { name: 'Escape',                     abbreviation: '', display: '^[', byte: 27 },
  FileSeperator:            { name: 'File Seperator',             abbreviation: '', display: '^\\', byte: 28 },
  GroupSeperator:           { name: 'Group Seperator',            abbreviation: '', display: '^]', byte: 29 },
  RecordSeperator:          { name: 'Record Seperator',           abbreviation: '', display: '^^', byte: 30 },
  UnitSeperator:            { name: 'Unit Seperator',             abbreviation: '', display: '^_', byte: 31 },
  Space:                    { name: 'Space',                      abbreviation: '', display: ' ', byte: 32 },
  ExclamationMark:          { name: 'Exclamation Mark',           abbreviation: '', display: '!', byte: 33 },
  Quotes:                   { name: 'Quotes',                     abbreviation: '', display: '"', byte: 34 },
  Hash:                     { name: 'Hash',                       abbreviation: '', display: '#', byte: 35 },
  Dollar:                   { name: 'Dollar',                     abbreviation: '', display: '$', byte: 36 },
  Percent:                  { name: 'Percent',                    abbreviation: '', display: '%', byte: 37 },
  Ampersand:                { name: 'Ampersand',                  abbreviation: '', display: '&', byte: 38 },
  Apostrophe:               { name: 'Apostrophe',                 abbreviation: '', display: '\'', byte: 39 },
  LeftParenthesis:          { name: 'Left Parenthesis',           abbreviation: '', display: '(', byte: 40 },
  RightParenthesis:         { name: 'Right Parenthesis',          abbreviation: '', display: ')', byte: 41 },
  Asterisk:                 { name: 'Asterisk',                   abbreviation: '', display: '*', byte: 42 },
  Plus:                     { name: 'Plus',                       abbreviation: '', display: '+', byte: 43 },
  Comma:                    { name: 'Comma',                      abbreviation: '', display: ',', byte: 44 },
  Dash:                     { name: 'Dash',                       abbreviation: '', display: '-', byte: 45 },
  Period:                   { name: 'Period',                     abbreviation: '', display: '.', byte: 46 },
  Slash:                    { name: 'Slash',                      abbreviation: '', display: '/', byte: 47 },
  Zero:                     { name: 'Zero',                       abbreviation: '', display: '0', byte: 48 },
  One:                      { name: 'One',                        abbreviation: '', display: '1', byte: 49 },
  Two:                      { name: 'Two',                        abbreviation: '', display: '2', byte: 50 },
  Three:                    { name: 'Three',                      abbreviation: '', display: '3', byte: 51 },
  Four:                     { name: 'Four',                       abbreviation: '', display: '4', byte: 52 },
  Five:                     { name: 'Five',                       abbreviation: '', display: '5', byte: 53 },
  Six:                      { name: 'Six',                        abbreviation: '', display: '6', byte: 54 },
  Seven:                    { name: 'Seven',                      abbreviation: '', display: '7', byte: 55 },
  Eight:                    { name: 'Eight',                      abbreviation: '', display: '8', byte: 56 },
  Nine:                     { name: 'Nine',                       abbreviation: '', display: '9', byte: 57 },
  Colon:                    { name: 'Colon',                      abbreviation: '', display: ':', byte: 58 },
  Semicolon:                { name: 'Semicolon',                  abbreviation: '', display: ';', byte: 59 },
  LessThan:                 { name: 'Less Than',                  abbreviation: '', display: '<', byte: 60 },
  Equals:                   { name: 'Equals',                     abbreviation: '', display: '=', byte: 61 },
  GreaterThan:              { name: 'Greater Than',               abbreviation: '', display: '>', byte: 62 },
  Questionmark:             { name: 'Question Mark',              abbreviation: '', display: '?', byte: 63 },
  At:                       { name: 'At',                         abbreviation: '', display: '@', byte: 64 },
  A:                        { name: 'A',                          abbreviation: '', display: 'A', byte: 65 },
  B:                        { name: 'B',                          abbreviation: '', display: 'B', byte: 66 },
  C:                        { name: 'C',                          abbreviation: '', display: 'C', byte: 67 },
  D:                        { name: 'D',                          abbreviation: '', display: 'D', byte: 68 },
  E:                        { name: 'E',                          abbreviation: '', display: 'E', byte: 69 },
  F:                        { name: 'F',                          abbreviation: '', display: 'F', byte: 70 },
  G:                        { name: 'G',                          abbreviation: '', display: 'G', byte: 71 },
  H:                        { name: 'H',                          abbreviation: '', display: 'H', byte: 72 },
  I:                        { name: 'I',                          abbreviation: '', display: 'I', byte: 73 },
  J:                        { name: 'J',                          abbreviation: '', display: 'J', byte: 74 },
  K:                        { name: 'K',                          abbreviation: '', display: 'K', byte: 75 },
  L:                        { name: 'L',                          abbreviation: '', display: 'L', byte: 76 },
  M:                        { name: 'M',                          abbreviation: '', display: 'M', byte: 77 },
  N:                        { name: 'N',                          abbreviation: '', display: 'N', byte: 78 },
  O:                        { name: 'O',                          abbreviation: '', display: 'O', byte: 79 },
  P:                        { name: 'P',                          abbreviation: '', display: 'P', byte: 80 },
  Q:                        { name: 'Q',                          abbreviation: '', display: 'Q', byte: 81 },
  R:                        { name: 'R',                          abbreviation: '', display: 'R', byte: 82 },
  S:                        { name: 'S',                          abbreviation: '', display: 'S', byte: 83 },
  T:                        { name: 'T',                          abbreviation: '', display: 'T', byte: 84 },
  U:                        { name: 'U',                          abbreviation: '', display: 'U', byte: 85 },
  V:                        { name: 'V',                          abbreviation: '', display: 'V', byte: 86 },
  W:                        { name: 'W',                          abbreviation: '', display: 'W', byte: 87 },
  X:                        { name: 'X',                          abbreviation: '', display: 'X', byte: 88 },
  Y:                        { name: 'Y',                          abbreviation: '', display: 'Y', byte: 89 },
  Z:                        { name: 'Z',                          abbreviation: '', display: 'Z', byte: 90 },
  LeftSquareBracket:        { name: 'Left Square Bracket',        abbreviation: '', display: '[', byte: 91 },
  Backslash:                { name: 'Backslash',                  abbreviation: '', display: '\\', byte: 92 },
  RightSquareBracket:       { name: 'Right Square Bracket',       abbreviation: '', display: ']', byte: 93 },
  Caret:                    { name: 'Caret',                      abbreviation: '', display: '^', byte: 94 },
  Underscore:               { name: 'Underscore',                 abbreviation: '', display: '_', byte: 95 },
  AccentGrave:              { name: 'Accent Grave',               abbreviation: '', display: '`', byte: 96 },
  a:                        { name: 'a',                          abbreviation: '', display: 'a', byte: 97 },
  b:                        { name: 'b',                          abbreviation: '', display: 'b', byte: 98 },
  c:                        { name: 'c',                          abbreviation: '', display: 'c', byte: 99 },
  d:                        { name: 'd',                          abbreviation: '', display: 'd', byte: 100 },
  e:                        { name: 'e',                          abbreviation: '', display: 'e', byte: 101 },
  f:                        { name: 'f',                          abbreviation: '', display: 'f', byte: 102 },
  g:                        { name: 'g',                          abbreviation: '', display: 'g', byte: 103 },
  h:                        { name: 'h',                          abbreviation: '', display: 'h', byte: 104 },
  i:                        { name: 'i',                          abbreviation: '', display: 'i', byte: 105 },
  j:                        { name: 'j',                          abbreviation: '', display: 'j', byte: 106 },
  k:                        { name: 'k',                          abbreviation: '', display: 'k', byte: 107 },
  l:                        { name: 'l',                          abbreviation: '', display: 'l', byte: 108 },
  m:                        { name: 'm',                          abbreviation: '', display: 'm', byte: 109 },
  n:                        { name: 'n',                          abbreviation: '', display: 'n', byte: 110 },
  o:                        { name: 'o',                          abbreviation: '', display: 'o', byte: 111 },
  p:                        { name: 'p',                          abbreviation: '', display: 'p', byte: 112 },
  q:                        { name: 'q',                          abbreviation: '', display: 'q', byte: 113 },
  r:                        { name: 'r',                          abbreviation: '', display: 'r', byte: 114 },
  s:                        { name: 's',                          abbreviation: '', display: 's', byte: 115 },
  t:                        { name: 't',                          abbreviation: '', display: 't', byte: 116 },
  u:                        { name: 'u',                          abbreviation: '', display: 'u', byte: 117 },
  v:                        { name: 'v',                          abbreviation: '', display: 'v', byte: 118 },
  w:                        { name: 'w',                          abbreviation: '', display: 'w', byte: 119 },
  x:                        { name: 'x',                          abbreviation: '', display: 'x', byte: 120 },
  y:                        { name: 'y',                          abbreviation: '', display: 'y', byte: 121 },
  z:                        { name: 'z',                          abbreviation: '', display: 'z', byte: 122 },
  LeftCurlyBrace:           { name: 'Left Curly Brace',           abbreviation: '', display: '{', byte: 123 },
  Pipe:                     { name: 'Pipe',                       abbreviation: '', display: '|', byte: 124 },
  RightCurlyBrace:          { name: 'Right Curly Brace',          abbreviation: '', display: '}', byte: 125 },
  Tilde:                    { name: 'Tilde',                      abbreviation: '', display: '~', byte: 126 },
  Delete:                   { name: 'Delete',                     abbreviation: 'DEL', display: '^?', byte: 127 }
};

export default Characters;

export function getCharacter(byte): Character {
  return Object.values(Characters).find(c => c.byte == byte);
}
